name: daily-al
base: core18
version: '1.0'
summary: UnOfficial MyAnimeList App
description: UnOfficial MyAnimeList App
grade: stable
confinement: strict

apps:
  hello:
    command: bin/hello

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools