name: daily-al
base: core18
version: git
summary: UnOfficial MyAnimeList App
description: UnOfficial MyAnimeList App
confinement: strict
base: core18
grade: stable

apps:
  daily-al:
    command: ./dailyanimelist