name: daily-al
base: core18
version: '1.0'
summary: UnOfficial MyAnimeList App
description: UnOfficial MyAnimeList App
confinement: strict
grade: stable

apps:
  daily-al:
    command: ./dailyanimelist

parts:
  daily-al:
    source: .