name: daily-al
base: core20
version: '1.0'
summary: UnOfficial MyAnimeList App
description: UnOfficial MyAnimeList App
confinement: strict
grade: stable

apps:
  daily-al:
    extensions: [gnome-3-38]
    command: usr/bin/run/run.sh

parts:
  daily-al:
    plugin: dump
    source: .
    organize:
      run.sh: usr/bin/run
      dailanimelist: usr/bin/run
      data: usr/bin/run
      lib: usr/bin/run
    stage-packages:
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libepoxy0
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libsecret-1-0


